# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Node.js, GitHub Actions, and Azure App Service: https://aka.ms/nodejs-webapps-actions

name: Minimal Azure Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.0.0 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build (skip lint blocking) & export
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_DISABLE_ESLINT: 1
        run: |
          pnpm run build

      - name: Archive build
        run: zip -r build.zip .next public package.json next.config.*

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F146D823C76C44BAA695A70AFD34E569 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4BEA309DA8F54427B17CF25D2EF3715C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C2BA8E3D5E9A4F25846F6913A2C7F3E9 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'StockNewsApp'
          slot-name: 'Production'
          package: build.zip
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: false





