# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Node.js, GitHub Actions, and Azure App Service: https://aka.ms/nodejs-webapps-actions

name: Build and deploy Node app to Azure Web App - StockNewsApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Unset NODE_OPTIONS
        run: unset NODE_OPTIONS

      - name: Enable Corepack
        run: corepack enable 
      
      - name: use pnpm
        run: corepack prepare pnpm@10.0.0 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js
        run: pnpm run build
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            .
            !node_modules/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F146D823C76C44BAA695A70AFD34E569 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4BEA309DA8F54427B17CF25D2EF3715C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C2BA8E3D5E9A4F25846F6913A2C7F3E9 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'StockNewsApp'
          slot-name: 'Production'

          




